services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    ports:
      - 27017:27017
    volumes:
      - mongodb_db:/data/db
      - mongodb_configdb:/data/configdb
    restart: always

  rabbitmq:
    image: rabbitmq:management
    container_name: "rabbitmq"
    ports:
      - 4369:4369
      - 5672:5672
      - 25672:25672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=rallyeschema
      - RABBITMQ_DEFAULT_PASS=rallyeschema
    volumes:
      - rabbitmq:/var/lib/rabbitmq
    restart: always

  rallye-schema-response-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: rallye-schema-response-service:local
    container_name: "rallye-schema-response-service"
    ports:
      - 8443:8443
    depends_on:
      - mongodb
      - rabbitmq
      - rallye-schema-form-processing-service
    restart: always
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
      - "SSL_KEYSTORE_PASSWORD=changeit"
      - "FORM_PROCESSING_ENABLED=true"
      - "FORM_PROCESSING_URL=http://rallye-schema-form-processing-service:8080"
    volumes:
      - ./certs:/app/certs:ro

  rallye-schema-form-processing-service:
    build:
      context: ../form-processing-service
      dockerfile: Dockerfile
    image: rallye-schema-form-processing-service:local
    container_name: "rallye-schema-form-processing-service"
    restart: always

volumes:
  mongodb_db:
  mongodb_configdb:
  rabbitmq:
