apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Docker\Docker\resources\bin\kompose.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Docker\Docker\resources\bin\kompose.exe convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - env:
        - name: RABBITMQ_PASSWORD
          value: rallyeschema
        - name: RABBITMQ_USERNAME
          value: rallyeschema
        image: bitnami/rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 4369
        - containerPort: 5672
        - containerPort: 25672
        - containerPort: 15672
        resources: {}
        volumeMounts:
        - mountPath: /bitnami
          name: rabbitmq
      restartPolicy: Always
      volumes:
      - name: rabbitmq
        persistentVolumeClaim:
          claimName: rabbitmq
status: {}
