version: "3"
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    ports:
    - 27017:27017
    restart: always
  app:
    image: form-scanner-service:0.0.1-SNAPSHOT
    ports:
    - 8080:8080
    links:
    - mongodb
    restart: always
    environment:
       - "SPRING_PROFILES_ACTIVE=docker"