apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Docker\Docker\resources\bin\kompose.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: form-scanner-service
  name: form-scanner-service
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Docker\Docker\resources\bin\kompose.exe convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: form-scanner-service
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        image: baalilion/form-scanner-service
        name: form-scanner-service
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
