services:
  form-processing-service:
    container_name: form-processing-service
    image: form-processing-service:local
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    restart: unless-stopped

