apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: rallye-schema-response-webapp
  name: rallye-schema-response-webapp
spec:
  type: LoadBalancer
  loadBalancerIP: 54.38.172.139
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    io.kompose.service: rallye-schema-response-webapp
status:
  loadBalancer:
    ingress:
      - ip: 54.38.172.139
