apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Docker\Docker\resources\bin\kompose.exe convert
      -f .\docker-compose-prod.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: rallye-schema-response-webapp
  name: rallye-schema-response-webapp
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Docker\Docker\resources\bin\kompose.exe convert
          -f .\docker-compose-prod.yml
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: rallye-schema-response-webapp
    spec:
      containers:
      - image: baalilion/rallye-schema-response-webapp
        name: rallye-schema-response-webapp
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
