apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    io.kompose.service: rallye-schema-response-webapp
  name: rallye-schema-response-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rallye-schema-response-webapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Program Files\Kompose\kompose.exe convert
        kompose.version: 1.20.0 (f3d54d784)
      creationTimestamp: null
      labels:
        io.kompose.service: rallye-schema-response-webapp
    spec:
      containers:
      - image: baalilion/rallye-schema-response-webapp
        name: rallye-schema-response-webapp
        ports:
        - containerPort: 80
        resources: {}
        volumeMounts:
        - mountPath: /app
          name: rallye-schema-response-webapp-app
        - mountPath: /usr/share/nginx/html/config
          name: rallye-schema-response-webapp-config
        - mountPath: /app/node_modules
          name: rallye-schema-response-webapp-claim2
      restartPolicy: Always
      volumes:
      - name: rallye-schema-response-webapp-app
        persistentVolumeClaim:
          claimName: rallye-schema-response-webapp-app
      - name: rallye-schema-response-webapp-config
        persistentVolumeClaim:
          claimName: rallye-schema-response-webapp-config
      - name: rallye-schema-response-webapp-claim2
        persistentVolumeClaim:
          claimName: rallye-schema-response-webapp-claim2
status: {}
