#############
### build ###
#############

# base image
FROM node:20-slim as build

# set working directory
WORKDIR /app

# install dependencies
COPY package.json package-lock.json ./
RUN npm ci

# copy app
COPY . .

# generate build (prod)
RUN npm run build -- --configuration production

############
### prod ###
############

# base image
FROM nginx:alpine

# copy artifact build from the 'build environment'
# Copie le build Angular vers nginx (adapté au outputPath défini dans angular.json)
COPY --from=build /app/dist/rallye-webapp/ /usr/share/nginx/html

# Copy the default nginx.conf
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

# expose ports 80 (redirect) et 443 (TLS)
EXPOSE 80 443

# run nginx
CMD ["nginx", "-g", "daemon off;"]
