apiVersion: v1
kind: Service
metadata:
  labels:
    app: rallye-webapp
  name: rallye-webapp
spec:
  type: LoadBalancer
  loadBalancerIP: 54.38.172.139
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: rallye-webapp
