apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rallye-webapp
    storage: configuration
  name: rallye-webapp-config
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
