version: '3.7'
services:
  rallye-schema-response-webapp:
    container_name: "rallye-schema-response-webapp"
    image: rallye-schema-response-webapp:dev
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4201:4200'
