export enum PerformanceRangeType {
  VALUE = 'VALUE',
  BEGIN_UP_RANK = 'BEGIN_UP_RANK',
  BEGIN_DOWN_RANK = 'BEGIN_DOWN_RANK',
  END_UP_RANK = 'END_UP_RANK',
  END_DOWN_RANK = 'END_DOWN_RANK',
  PERF_UP_RANK = 'PERF_UP_RANK',
  PERF_DOWN_RANK = 'PERF_DOWN_RANK'
}
