apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb
    storage: database
  name: mongodb-db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
