apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mongodb
    storage: configuration
  name: mongodb-configdb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1000Mi
